import { StyleSheet } from 'react-native';

export const COLORS: string[] = ['#2563eb', '#16a34a', '#dc2626', '#9333ea', '#ea580c', '#0891b2', '#4f46e5', '#ec4899', '#14b8a6', '#84cc16', '#f59e0b', '#8b5cf6', '#10b981', '#0ea5e9'];

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#f8fafc' },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  header: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 18, paddingTop: 30, paddingBottom: 12, backgroundColor: '#111827' },
  hamburgerButton: { padding: 4, marginRight: 6 },
  hamburgerText: { fontSize: 26, color: '#ffffff' },
  appTitle: { fontSize: 22, fontWeight: '800', color: '#ffffff' },
  content: { padding: 14, paddingBottom: 36 },
  card: { backgroundColor: '#ffffff', borderRadius: 18, padding: 16, marginBottom: 12, shadowColor: '#000', shadowOpacity: 0.05, shadowRadius: 12, shadowOffset: { width: 0, height: 4 }, elevation: 2 },
  row: { flexDirection: 'row', alignItems: 'center' },
  rowBetween: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  rowGap: { flexDirection: 'row', gap: 10 },
  actionRow: { flexDirection: 'row', gap: 10, marginTop: 14 },
  flex1: { flex: 1 },
  weekTitleWrap: { alignItems: 'center', flex: 1 },
  weekTitle: { color: '#6b7280', fontWeight: '700', fontSize: 12, textTransform: 'uppercase' },
  weekRange: { fontSize: 16, fontWeight: '800', color: '#111827', textAlign: 'center' },
  statsRow: { flexDirection: 'row', gap: 10, marginTop: 16 },
  stat: { flex: 1, backgroundColor: '#f3f4f6', borderRadius: 14, padding: 12 },
  statValue: { fontSize: 18, fontWeight: '800', color: '#111827' },
  statLabel: { color: '#6b7280', marginTop: 2, fontSize: 12 },
  sectionTitle: { fontSize: 18, fontWeight: '800', color: '#111827' },
  emptyText: { marginTop: 10, color: '#9ca3af' },
  link: { color: '#2563eb', fontWeight: '800' },
  button: { backgroundColor: '#2563eb', borderRadius: 14, paddingVertical: 12, paddingHorizontal: 14, alignItems: 'center', justifyContent: 'center', flexShrink: 1 },
  buttonSecondary: { backgroundColor: '#eff6ff' },
  buttonDanger: { backgroundColor: '#dc2626' },
  buttonText: { color: '#ffffff', fontWeight: '800' },
  buttonSecondaryText: { color: '#2563eb' },
  smallButton: { backgroundColor: '#f3f4f6', paddingVertical: 8, paddingHorizontal: 10, borderRadius: 12 },
  smallButtonText: { color: '#111827', fontWeight: '800', fontSize: 12 },
  shiftItem: { flexDirection: 'row', gap: 10, backgroundColor: '#f9fafb', borderRadius: 14, padding: 12, marginTop: 10 },
  colorBar: { width: 5, borderRadius: 10 },
  colorDot: { width: 14, height: 14, borderRadius: 7, marginRight: 10 },
  itemTitle: { fontSize: 16, fontWeight: '800', color: '#111827' },
  itemSubtitle: { color: '#4b5563', marginTop: 3 },
  itemMeta: { color: '#6b7280', marginTop: 3, fontSize: 12 },
  modalHeader: { paddingHorizontal: 18, paddingVertical: 14, backgroundColor: '#ffffff', borderBottomWidth: 1, borderBottomColor: '#e5e7eb', flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  modalTitle: { fontSize: 20, fontWeight: '800', color: '#111827' },
  field: { marginBottom: 12 },
  label: { color: '#374151', fontWeight: '700', marginBottom: 6 },
  input: { backgroundColor: '#f9fafb', borderWidth: 1, borderColor: '#e5e7eb', borderRadius: 14, paddingHorizontal: 12, paddingVertical: 12, fontSize: 15, color: '#111827' },
  textarea: { minHeight: 80, textAlignVertical: 'top' },
  choice: { paddingVertical: 10, paddingHorizontal: 12, borderRadius: 999, backgroundColor: '#f3f4f6', marginRight: 8, marginBottom: 4 },
  choiceActive: { backgroundColor: '#111827' },
  choiceText: { color: '#374151', fontWeight: '700' },
  choiceTextActive: { color: '#ffffff' },
  spacer: { height: 12 },
  colorPreview: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#f9fafb', borderWidth: 1, borderColor: '#e5e7eb', borderRadius: 14, padding: 10 },
  colorPreviewSwatch: { width: 32, height: 32, borderRadius: 8, marginRight: 12 },
  colorPreviewText: { fontSize: 15, color: '#111827', fontWeight: '600' },
  colorPickerContainer: { flex: 1, paddingHorizontal: 24, justifyContent: 'center' },
  colorPickerActions: { paddingHorizontal: 24, paddingBottom: 24 },
  filterRow: { flexDirection: 'row', gap: 8, marginTop: 12 },
  filterInput: { flex: 1, height: 40, paddingVertical: 0 },
  sortButton: { backgroundColor: '#f3f4f6', borderRadius: 14, paddingHorizontal: 14, alignItems: 'center', justifyContent: 'center' },
  sortButtonText: { color: '#111827', fontWeight: '800', fontSize: 13 },
  timePickerButton: { backgroundColor: '#f9fafb', borderWidth: 1, borderColor: '#e5e7eb', borderRadius: 14, padding: 14, alignItems: 'center' },
  stepperContainer: { backgroundColor: '#f9fafb', borderWidth: 1, borderColor: '#e5e7eb', borderRadius: 14, paddingVertical: 4, paddingHorizontal: 8, alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', 'paddingTop': 14, 'paddingBottom': 14 },
  stepperArrow: { paddingHorizontal: 16, paddingVertical: 0 },
  stepperArrowText: { fontSize: 12, fontWeight: '800', color: '#374151' },
  stepperValue: { fontSize: 20, fontWeight: '800', color: '#111827', paddingVertical: 0 },
  timePickerButtonText: { fontSize: 20, fontWeight: '800', color: '#111827' },
  timePickerColumns: { flexDirection: 'row', flex: 1, alignItems: 'center', paddingHorizontal: 24, gap: 4, justifyContent: 'center' },
  timePickerColumn: { maxHeight: 280, width: 100 },
  timePickerSeparator: { fontSize: 28, fontWeight: '800', color: '#111827', marginHorizontal: 4 },
  timePickerItem: { paddingVertical: 14, paddingHorizontal: 20, borderRadius: 12, alignItems: 'center', marginVertical: 2 },
  timePickerItemActive: { backgroundColor: '#111827' },
  timePickerItemText: { fontSize: 20, fontWeight: '700', color: '#374151' },
  timePickerItemTextActive: { color: '#ffffff' },
  langHeaderButton: { padding: 4, marginLeft: 6 },
  langHeaderFlag: { fontSize: 24 },
  langModalContent: { padding: 24, gap: 12 },
  langModalOption: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#ffffff', borderRadius: 18, padding: 18, shadowColor: '#000', shadowOpacity: 0.05, shadowRadius: 12, shadowOffset: { width: 0, height: 4 }, elevation: 2, gap: 14 },
  langModalOptionActive: { borderWidth: 2, borderColor: '#111827' },
  langModalFlag: { fontSize: 32 },
  langModalLabel: { fontSize: 18, fontWeight: '700', color: '#111827', flex: 1 },
  langModalLabelActive: { color: '#111827' },
  langModalCheck: { fontSize: 20, fontWeight: '800', color: '#111827' },
  menuWrapper: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, zIndex: 100 },
  menuBackdrop: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(0,0,0,0.4)' },
  menuDrawer: { position: 'absolute', top: 0, left: 0, bottom: 0, width: 280, backgroundColor: '#ffffff', paddingTop: 20, shadowColor: '#000', shadowOpacity: 0.15, shadowRadius: 20, shadowOffset: { width: 2, height: 0 }, elevation: 8 },
  menuHeaderSection: { paddingHorizontal: 24, paddingBottom: 16, borderBottomWidth: 1, borderBottomColor: '#e5e7eb', marginBottom: 8 },
  menuTitle: { fontSize: 22, fontWeight: '800', color: '#111827' },
  menuItem: { paddingHorizontal: 24, paddingVertical: 14, borderRadius: 12, marginHorizontal: 8, marginVertical: 2 },
  menuItemActive: { backgroundColor: '#111827' },
  menuItemText: { fontSize: 17, fontWeight: '700', color: '#374151' },
  menuItemTextActive: { color: '#ffffff' }
});
